name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
  ECR_REPOSITORY: "fastapi"
  EC2_IP: "54.91.175.71"
  # ECR_REGISTRY: 
  # ECR_REPOSITORY:
  # IMAGE_TAG:
  

jobs:

  # test:
  #   name: Run FastAPI test
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Install Make
  #       run: sudo apt-get update && sudo apt-get install -y make

  #     - name: Set up Python
  #       uses: actions/setup-python@v5.4.0
  #       with:
  #         python-version: 3.13

  #     - name: Install Dependencies
  #       run: pip install -r src/requirements.txt 

  #     - name: Run Pytest with make
  #       run: make test

  build:
    name: Build and deploy to EC2
    runs-on: ubuntu-latest
    # environment: dev
    # needs: test
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}

        run: |
            # Build a docker container and
            # push it to ECR so that it can
            # be deployed to EC2.

            docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
            docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
            # echo "$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
            echo "image=$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG" >> $GITHUB_OUTPUT
            
      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > deploy_key.pem
          chmod 400 deploy_key.pem
          
      - name: Connect to EC2 & Deploy Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@${{ env.EC2_IP }} << 'EOF'
            
            # Configure AWS Credentials
            sudo aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            sudo aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            sudo aws configure set region ${{ env.AWS_REGION }}
          
            # login to ECR
            sudo aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 941377147642.dkr.ecr.us-east-1.amazonaws.com
            
            # Stop running docker (if any)
            sudo docker ps -aq | xargs -r sudo docker stop
            sudo docker ps -aq | xargs -r sudo docker rm

            #Run new docker image
            sudo docker run -d -p 80:8000 ${{ steps.build-image.outputs.image }}
          EOF
          
  # build-and-push:
  #   name: Build & Push Docker Image to ECR
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Login to Amazon ECR
  #       run: |
  #         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

  #     - name: Build & Tag Docker Image
  #       run: |
  #         docker build -t my-fastapi-app .
  #         docker tag my-fastapi-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fastapi-app:latest

  #     - name: Push Docker Image to ECR
  #       run: |
  #         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fastapi-app:latest

  # deploy:
  #   name: Deploy to EC2
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Set Up SSH Key
  #       run: |
  #         echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
  #         chmod 600 private_key.pem

      # - name: Connect to EC2 & Deploy Docker Image
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
      #       echo "Logging in to ECR..."
      #       aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
            
      #       echo "Pulling new Docker image..."
      #       docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fastapi-app:latest
            
      #       echo "Stopping and removing previous container..."
      #       docker stop fastapi_app || true
      #       docker rm fastapi_app || true
            
      #       echo "Running new container..."
      #       docker run -d --name fastapi_app -p 80:80 ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-fastapi-app:latest
      #     EOF
